import fs from "fs/promises";
import path from "path";
import { PACKS_DIR, RESEARCH_DIR, VAULT_ROOT, parseFile, listResearchFilesForDate } from "./loader";
import type { DailyPack, GoldenSections } from "./types";

function fmtSections(s: GoldenSections, prefix = "###"): string {
  const parts: string[] = [];
  if (s.meaning) parts.push(`${prefix} Meaning\n${s.meaning}`);
  if (s.literal) parts.push(`${prefix} Literal\n${s.literal}`);
  if (s.natural) parts.push(`${prefix} Natural\n${s.natural}`);
  if (s.grammarSkeleton) parts.push(`${prefix} Grammar Skeleton\n${s.grammarSkeleton}`);
  if (s.practiceMove) parts.push(`${prefix} Practice Move\n${s.practiceMove}`);
  if (s.saveableCard) parts.push(`${prefix} Saveable Card\n${s.saveableCard}`);
  return parts.join("\n\n");
}

export function renderDailyPackMarkdown(pack: DailyPack): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("kind: day-pack");
  lines.push(`date: ${pack.date}`);
  lines.push("locale: vallarta");
  lines.push("source: app");
  lines.push("status: ready");
  lines.push(`generated_at: ${pack.generatedAt}`);
  lines.push(`source_count: ${pack.sources.length}`);
  lines.push("---");
  lines.push("");
  lines.push(`> **Auto-generated by app on ${pack.generatedAt} from ${pack.sources.length} research files.**`);
  lines.push("> Do not hand-edit this file — your edits will be overwritten on the next sync.");
  lines.push("> To change the day pack, edit the source files in `11_Research/" + pack.date + "/`.");
  lines.push("");

  if (
    pack.personalization.learnerProfileExcerpt ||
    pack.personalization.recentWords.length ||
    pack.personalization.recentGrammar.length
  ) {
    lines.push("## Personalization");
    if (pack.personalization.learnerProfileExcerpt) {
      lines.push("### Learner profile");
      lines.push(pack.personalization.learnerProfileExcerpt);
      lines.push("");
    }
    if (pack.personalization.recentWords.length) {
      lines.push("- Recent words: " + pack.personalization.recentWords.map((w) => w.word).join(", "));
    }
    if (pack.personalization.recentGrammar.length) {
      lines.push("- Recent grammar: " + pack.personalization.recentGrammar.map((g) => g.title).join("; "));
    }
    lines.push("");
  }

  if (pack.airport.length) {
    lines.push("## Airport");
    for (const a of pack.airport) {
      lines.push(`### ${a.title}`);
      lines.push(`*Source: \`${a.sourcePath}\`*`);
      lines.push("");
      lines.push(fmtSections(a.sections, "####"));
      lines.push("");
    }
  }

  if (pack.atelier.length) {
    lines.push("## Atelier");
    for (const a of pack.atelier) {
      lines.push(`### ${a.author}${a.work ? " — " + a.work : ""}: ${a.title}`);
      lines.push(`*Source: \`${a.sourcePath}\`*`);
      lines.push("");
      lines.push(fmtSections(a.sections, "####"));
      lines.push("");
    }
  }

  if (pack.bridge.length) {
    lines.push("## Bridge");
    for (const b of pack.bridge) {
      lines.push(`### Pair: ${b.pairId}`);
      lines.push(`*Source: \`${b.sourcePath}\`*`);
      lines.push("");
      lines.push("#### Travel Half");
      lines.push(fmtSections(b.travel, "#####"));
      lines.push("");
      lines.push("#### Literary Half");
      lines.push(fmtSections(b.literary, "#####"));
      lines.push("");
    }
  }

  if (pack.vocab.length) {
    lines.push("## Vocabulary");
    for (const v of pack.vocab) {
      lines.push(`### ${v.slug}`);
      for (const it of v.items) {
        lines.push(`- **${it.front}** — ${it.back}${it.note ? ` *(${it.note})*` : ""}`);
      }
      lines.push("");
    }
  }

  if (pack.grammar.length) {
    lines.push("## Grammar");
    for (const g of pack.grammar) {
      lines.push(`### ${g.title}`);
      lines.push(fmtSections(g.sections, "####"));
      lines.push("");
    }
  }

  if (pack.errors.length) {
    lines.push("## Skipped (parse errors)");
    for (const e of pack.errors) {
      const loc = e.line ? `:${e.line}` : "";
      lines.push(`- \`${e.file}${loc}\` — ${e.message}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** Write the rendered pack to 08_ProjectPacks/<date>.md. Returns 'built' | 'updated'. */
export async function writeDailyPackFile(pack: DailyPack): Promise<"built" | "updated"> {
  await fs.mkdir(PACKS_DIR, { recursive: true });
  const out = path.join(PACKS_DIR, `${pack.date}.md`);
  let existed = false;
  try { await fs.access(out); existed = true; } catch { /* not present */ }
  await fs.writeFile(out, renderDailyPackMarkdown(pack), "utf8");
  return existed ? "updated" : "built";
}

/**
 * Move integrated source files under 08_ProjectPacks/<date>/sources/.
 * Walks 11_Research/<date>/ recursively (matching the loader) so files in
 * subfolders also get relocated when status:integrated is set. Preserves the
 * subpath under 11_Research/<date>/ when moving.
 */
export async function moveIntegratedSources(date: string): Promise<{ moved: string[] }> {
  const moved: string[] = [];
  const srcRoot = path.join(RESEARCH_DIR, date);
  const destRoot = path.join(PACKS_DIR, date, "sources");
  const files = await listResearchFilesForDate(date);
  for (const abs of files) {
    try {
      const p = await parseFile(abs);
      if (p.frontmatter.status !== "integrated") continue;
      const relUnderDate = path.relative(srcRoot, abs);
      const dest = path.join(destRoot, relUnderDate);
      await fs.mkdir(path.dirname(dest), { recursive: true });
      await fs.rename(abs, dest);
      moved.push(path.relative(VAULT_ROOT, dest));
    } catch {
      /* parse errors handled by the loader path */
    }
  }
  return { moved };
}
